1. Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np

def add_matrix(mat1, mat2):
    if mat1.shape == mat2.shape:
        result = np.add(mat1,mat2)
        print("Final Matrix:")
        print(result)
    else:
        print("Matrices are not in the same shapes")

In [8]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[7,6,5],[4,3,2],[1,0,-1]])

In [9]:
add_matrix(mat1, mat2)

Final Matrix:
[[8 8 8]
 [8 8 8]
 [8 8 8]]


2. Write a Python Program to Multiply Two Matrices?

In [14]:
import numpy as np

def multipy_matrix(mat1, mat2):
    if mat1.shape[1] == mat2.shape[0]:
        result = np.dot(mat1,mat2)
        print("Final Matrix:")
        print(result)
    else:
        print("Matrices are not in the same shapes")

In [15]:
multipy_matrix(mat1,mat2)

Final Matrix:
[[18 12  6]
 [54 39 24]
 [90 66 42]]


In [16]:
mat3 = np.array([[7,6,5],[4,3,2]])

In [17]:
multipy_matrix(mat1,mat3)

Matrices are not in the same shapes


3. Write a Python Program to Transpose a Matrix?

In [18]:
import numpy as np

def traspose_matrix(mat):
    trans_matrix = np.transpose(mat)
    print("Transpose Matrix:")
    print(trans_matrix)

In [19]:
traspose_matrix(mat1)

Transpose Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
traspose_matrix(mat2)

Transpose Matrix:
[[ 7  4  1]
 [ 6  3  0]
 [ 5  2 -1]]


In [21]:
traspose_matrix(mat3)

Transpose Matrix:
[[7 4]
 [6 3]
 [5 2]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [22]:
def sort_words(words):
    sorted_words = sorted(words)
    return sorted_words

In [24]:
word_list = ['elderberry', 'date', 'banana', 'apple', 'cherry']
sorted_words = sort_words(word_list)

print("Original words:", word_list)
print("Sorted words:", sorted_words)

Original words: ['elderberry', 'date', 'banana', 'apple', 'cherry']
Sorted words: ['apple', 'banana', 'cherry', 'date', 'elderberry']


5. Write a Python Program to Remove Punctuation From a String?

In [26]:
import string

def remove_punctuation(text):
    no_punct = "".join([char for char in text if char not in string.punctuation])
    return no_punct

In [28]:
text = "Hello! This is a string, with 'punctuation' marks."
no_punct = remove_punctuation(text)

print("Original text:", text)
print("After removed:", no_punct)

Original text: Hello! This is a string, with 'punctuation' marks.
After removed: Hello This is a string with punctuation marks
